# ███████╗ █████╗ ██╗     ██╗     ██████╗  █████╗  ██████╗██╗  ██╗    ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
# ██╔════╝██╔══██╗██║     ██║     ██╔══██╗██╔══██╗██╔════╝██║ ██╔╝    ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
# █████╗  ███████║██║     ██║     ██████╔╝███████║██║     █████╔╝     ███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
# ██╔══╝  ██╔══██║██║     ██║     ██╔══██╗██╔══██║██║     ██╔═██╗     ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
# ██║     ██║  ██║███████╗███████╗██████╔╝██║  ██║╚██████╗██║  ██╗    ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
# ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝
# Made by CandiesJar | Github: github.com/sasi2006166 | Discord: discord.candydevelopment.eu | Telegram: @CandiesJar

Fallback_Server:
  use_stats: true # Enabling this will make me know how many people is using my plugin.
  command_tab_complete: true
  command_without_permission: false # Hide /fs command when a player doesn't have permission
  check_updates: true
  command_permission: "fallback.admin"

Hub:
  lobbies:
    server_list:
      - lobby1
      - lobby2
      - lobby3
  commands:
    enable_command: true # Use this if you want to use hub command (REQUIRES PROXY REBOOT).
    command_aliases: # Add command aliases here. (REQUIRES PROXY REBOOT)
      - lobby
      - hub
  enable_disabled_servers: true # Will disable the hub command for specified servers. (REQUIRES PROXY REBOOT).
  disabled_servers:
    hack_control: # Add server here that shouldn't have command enabled, don't forget to add also hub aliases under it.
      - lobby
      - hub
    hack_control_2:
      - lobby
      - hub
# TOP feature, you can disable any command you want in specified servers! Just add it without / under the server name!