# ███████╗ █████╗ ██╗     ██╗     ██████╗  █████╗  ██████╗██╗  ██╗    ███████╗███████╗██████╗ ██╗   ██╗███████╗██████╗
# ██╔════╝██╔══██╗██║     ██║     ██╔══██╗██╔══██╗██╔════╝██║ ██╔╝    ██╔════╝██╔════╝██╔══██╗██║   ██║██╔════╝██╔══██╗
# █████╗  ███████║██║     ██║     ██████╔╝███████║██║     █████╔╝     ███████╗█████╗  ██████╔╝██║   ██║█████╗  ██████╔╝
# ██╔══╝  ██╔══██║██║     ██║     ██╔══██╗██╔══██║██║     ██╔═██╗     ╚════██║██╔══╝  ██╔══██╗╚██╗ ██╔╝██╔══╝  ██╔══██╗
# ██║     ██║  ██║███████╗███████╗██████╔╝██║  ██║╚██████╗██║  ██╗    ███████║███████╗██║  ██║ ╚████╔╝ ███████╗██║  ██║
# ╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝╚═════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝    ╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝
# Made by CandiesJar | Github: github.com/sasi2006166 | Discord: https://discord.gg/fmUc6g3x | Telegram: @CandiesJar

Fallback_Server:
  command_tab_complete: true
  command_without_permission: false # Hide /fs command when a player doesn't have permission
  check_updates: true
  command_permission: "fallback.admin"
  reload_permission: "fallback.reload"

Hub:
  server_list:
    - lobby1
    - lobby2
    - lobby3
  commands:
    enable_command: true # This flag requires a proxy reboot!
    command_aliases: # Customize /hub command, requires reboot!
      - lobby
      - hub
  enable_disabled_servers: true # Will disable the hub command for specified servers. (REQUIRES PROXY REBOOT).
  disabled_servers:
    hack_control: # Add server name with all command aliases or what command you want to disable, like /bungee
      - lobby
      - hub
    hack_control_2:
      - lobby
      - hub